### ISSUE TITLE
Supporting pandoc-types 1.22

### ISSUE THREAD

**Issue by ickc** [elliottslaughter/rust-pandoc-types#2]
Just trying to putting some potentially useful info here. No pressure:

# Links on new table AST

- PR
    - Feature request started here: jgm/pandoc#1024, jgm/pandoc-types#65
    - this is where the actual change of the AST happened: https://github.com/jgm/pandoc-types/pull/66/files?file-filters%5B%5D=.hs#diff-01f4ffe52cf097ab9ff89eebce394c86
    - pandoc 2.10 release note: https://github.com/jgm/pandoc/releases/tag/2.10
    - pandoc 2.11 release note (see HTML writer): https://github.com/jgm/pandoc/releases/tag/2.11
    - pandoc-types changelog: https://github.com/jgm/pandoc-types/blob/master/changelog
- def
    - https://hackage.haskell.org/package/pandoc-types-1.22/docs/Text-Pandoc-Definition.html
    - source: https://github.com/jgm/pandoc-types/blob/master/src/Text/Pandoc/Arbitrary.hs
    - doc on lua filters has some info on this: https://pandoc.org/lua-filters.html
    - See comments at https://github.com/jgm/pandoc-types/pull/66#issuecomment-611053332 and after on normalizing tables
- example ASTs:
    - https://github.com/jgm/pandoc-types/blob/master/test/test-pandoc-types.hs
    - https://github.com/jgm/pandoc/tree/master/test/tables

**Comment by ickc** [comment]
Just a warning that pandoc-types might experience yet another big change regarding table: jgm/pandoc-types#86. (Major changes in pandoc-types 1.21 & 1.22 are about table.)

So you may want to hold off a bit until the dust settled there.

**Comment by elliottslaughter** [comment]
Is this in a stable release or a PR? I think in general we'd want to stick to what's been released.

**Comment by ickc** [comment]
Two major versions has been released. But as in the link above they might want to change that again. So might be wise to wait until that's settled.

For details see the links above, Eg pandoc types change logs.
